# 作成したDiscord BOTのトークンキーと各メッセージチャンネルのIDを指定してください。
# 例) TOKEN: gesnkbsgha.geraiihovnegrh-greaihv
#     MESSAGE_SYNC_CHANNEL: 883456154786536455
#     WHITELIST_CHANNEL: 987645589754668455
TOKEN: XXXXXXXXXXX.XXXXXX.XXXXXXXXXXX
SERVER_ID: XXXXXXXXXXXXXXXXXX
BOT_STATUS: "hogehoge"
MESSAGE_SYNC_CHANNEL: XXXXXXXXXXX
WHITELIST_CHANNEL: XXXXXXXXXXX
SERVER_STATUS:
  SYNC_BOOL: false
  SYNC_CHANNEL: XXXXXXXXXXX
  ENABLE_TEXT: "🟢サーバーが起動中"
  DISABLE_TEXT: "🔴サーバーが停止中"
SERVER_INFO:
  SERVER_NOTICE_BOOL : true
  STAT_MESS : ":green_circle: サーバーが起動しました"
  CLOSE_MESS : ":red_circle: サーバーが停止しました"
USER_INFO:
  USER_NOTICE_BOOL : true
  JOIN_NOTICE:
    TYPE: "embed"
    MESSAGE: "&{UserName}がゲームに参加しました!いらっしゃい!"
    COLOR: "#37ab58"
  LEAVE_NOTICE:
    TYPE: "embed"
    MESSAGE : "&{UserName}がゲームを離れました。バイバイ"
    COLOR: "#c44949"
MESSAGE_TYPE:
  D2M : "<&{UserName}>&{message}"
  M2D : "<&{UserName}>&{message}"
  DISCORD_ONLY : "¥"
  MINECRAFT_ONLY : "*"
CMD:
  CMD_NOTICE_BOOL : true
  CMD_NOTICE_MESS : "がコマンドを利用した! : "
ORE:
  GET_NOTICE:
    SEND_MINECRAFT: true
    SEND_DISCORD: true
    NOTICE_LIST:
      - name: "DIAMOND_ORE"
        sendText: "&{UserName}がダイヤモンドを見つけた!!"
      - name: "DEEPSLATE_DIAMOND_ORE"
        sendText: "&{UserName}が深成岩のダイヤモンドを見つけた!!"
BED:
  SLEEP_NOTICE: true