# 作成したDiscord BOTのトークンキーと各メッセージチャンネルのIDを指定してください。
# 例) TOKEN: gesnkbsgha.geraiihovnegrh-greaihv
#     MESSAGE_SYNC_CHANNEL: 883456154786536455
#     WHITELIST_CHANNEL: 987645589754668455
TOKEN: XXXXXXXXXXX.XXXXXX.XXXXXXXXXXX
MESSAGE_SYNC_CHANNEL: XXXXXXXXXXX
WHITELIST_CHANNEL: XXXXXXXXXXX
SERVER_INFO:
  SERVER_NOTICE_BOOL : "true"
  STAT_MESS : ":green_circle: サーバーが起動しました"
  CLOSE_MESS : ":red_circle: サーバーが停止しました"
USER_INFO:
  USER_NOTICE_BOOL : "true"
  JOIN_MESS : "がゲームに参加しました!いらっしゃい!"
  LEAVE_MESS : "がゲームを離れました。バイバイ"
MESSAGE_TYPE:
  D2M : "<&{UserName}>&{message}"
  M2D : "<&{UserName}>&{message}"
  DISCORD_ONLY : "¥"
  MINECRAFT_ONLY : "*"
CMD:
  CMD_NOTICE_BOOL : "true"
  CMD_NOTICE_MESS : "がコマンドを利用した! : "
ORE:
  GET_NOTICE:
    SEND_MINECRAFT: "true"
    SEND_DISCORD": "true"
BED:
  SLEEP_NOTICE: "true"